import { Aleo } from "next/font/google";
import "./globals.css";
import Footer from "@/src/components/Footer/Footer";
import Title from "@/src/components/Title/Title";

const aleo = Aleo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={aleo.className}>

        <Title/>
             {children}
        <Footer/>
      

     </body>
</html>
  );
}


 // <html lang="en">
    //   <body className={inter.className}>{children}</body>
    // </html>